### DISCUSSION TITLE
issue: CUDA out of memory when using optuna to do hyperparam search for LLM LoRA

### DISCUSSION THREAD

**Discussion by zwille014** [optuna/optuna#5932] [Q&A] [answered]
### Expected behavior

Our GPU has 24 memory in total. We load "Llama-3.2-3B-instruct" full precision every trial (It will consume approximately 12GB of GPU memory), and use torch.cuda.empty_cache() to clear CPU memory after each trial to avoid memory leak. It should not encounter any out-of-memory issues. It should complete all the hyperparameter search trials. Did optuna cause the problem? Is there any solution?
BTW: I didn't meet OOM issue when i trained the model, the training process finishes as expected. The OOM only occurs when using optuna to do the hyperparam search.

### Environment

- Optuna version: 4.1.0
- Python version: 3.10.14
- OS: Linux
- (Optional) Other libraries and their versions:  transformers 4.45.2, peft 0.14.0

### Error messages, stack traces, or logs

```shell
OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacity of 21.98 GiB of which 40.44 MiB is free. Including non-PyTorch memory, this process has 21.93 GiB memory in use. Of the allocated memory 20.93 GiB is allocated by PyTorch, and 715.86 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.
```

### Steps to reproduce

```python

model_path = "Llama-3.2-3B-instruct"

def objective(trial):
    # Define the search space for hyperparameters
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-4)
    per_device_train_batch_size = trial.suggest_categorical('batch_size', [8, 16, 32])

    # Define the model
    cur_base_model = LlamaForTokenClassification.from_pretrained(
        model_path
    )
    
    cur_config = {
        "peft_type": "LORA",
        "inference_mode": False,
        "r": trial.suggest_categorical('lora_r', [8, 16]),
        "lora_alpha": 16,
        "lora_dropout": 0.05,
        "bias": "none",    
        "target_modules": [
            "q_proj",
            "v_proj"
        ]
    }
    
    cur_peft_config = get_peft_config(cur_config)
    cur_peft_model = PeftModelForTokenClassification(cur_base_model, cur_peft_config)
    
    hpo_training_args = TrainingArguments(
        output_dir = 'trained',
        learning_rate = 1e-4,
        per_device_train_batch_size = per_device_train_batch_size,
        per_device_eval_batch_size = 2,
        num_train_epochs = 5,
        logging_steps=1,
        weight_decay = 0.001,
        report_to="none"
    )

    # Define the Trainer
    trainer = Trainer(
        model=cur_peft_model,
        args=hpo_training_args,
        train_dataset=tokenized_train.shard(index=1, num_shards=10),
        eval_dataset=tokenized_eval.shard(index=1, num_shards=10),
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=lambda preds: eval_util.compute_metrics(preds, mappings)
    )

    # Train and evaluate
    train_results = trainer.train()
    eval_results = trainer.evaluate()
    
    res = eval_results['eval_loss']

    # Manually clear GPU memory after each trial to avoid memory leaks
    del cur_peft_model
    torch.cuda.empty_cache()
    
    return res

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=10, gc_after_trial=True, callbacks=[lambda study, trial: gc.collect()])  # 10 trials as an example
print(f"Best hyperparameters: {study.best_params}")
```

**Comment by nzw0301** [comment]
>  Did optuna cause the problem?

I don't think so. I suggest checking GPU memory snapshots to investigate unexpected GPU memory usage, such as https://pytorch.org/docs/stable/torch_cuda_memory.html. I believe that removing the PEFT model instance is not enough; for example, the optimiser also uses a lot of GPUs.

**Reply by zwille014** [reply]
In the hyperparam search, why in first trial there is no issue, but when second trial begins, it starts to have OOM issue?  Also,  i didn't meet any oom issue when i only trained this model. The issue only happened when using optuna to do the hyperparam search.

**Reply by nzw0301** [reply]
because GPU memory is not completely free after the first trial.

**Reply by tahsintahsin** [reply]
hi @nzw0301 , I am experiencing the same issue. why is GPU memory not freed after the 1st trial ? And is there a way to achieve this if we are working in a limited GPU setup? thanks

**Reply by nzw0301** [reply]
Could you try things in my first answer?

**Reply by tahsintahsin** [reply]
Hi @nzw0301 I tried using memory snapshots. When I visualized it, Tthe memory doesnt seem to be freed after the trial . Anything else I should check from the snapshots ? 

I also observed the live memory usage during hyperparameter search 
If I set number of trials=1, it works properly. However, increasing it to 2 trials, n_trials=2 created issue again, which showed me that the memory is not being cleaned between runs. 
Also, I am working on Jupyter notebook environment, if it matters

**Reply by nzw0301** [reply]
Thanks. That sounds strange, are you sure that the GPU memory is not used at each trial's beginning in the visualisation?

**Reply by nzw0301** [reply]
If possible could you share the minimal reproducible code with us, ideally as a colab notebook?

**Reply by zwille014** [reply]
> If possible could you share the minimal reproducible code with us, ideally as a colab notebook?
@nzw0301 

tahsintahsin and i are in the same team. You can just follow the notebook i post above. 

And there are other observations. If the batch_size above 11, the OOM will happen. If the batch_size is less than or equal to 11,  all the trials will be executed and completed successfully.
We tried to remove all memory clean codes below:
`del cur_peft_model
 torch.cuda.empty_cache()`
All trials completed successfully again, if batch_size in each trial is less than or equal to 11.

And another thing is when batch_size = 10, and GPU memory usage is 21171MiB, and batch_size = 11 the GPU memory usage is 22301MiB. I believe that for every increase in batch size, the GPU memory usage will increase by approximately 1GB. (For Llama-3.2-3B-instruct)

**Reply by nzw0301** [reply]
Thank you for getting back to me. I'm not sure `del cur_peft_model torch.cuda.empty_cache()` remove all aches because the optimiser state and tensor data are still on GPU, right?
Anyway, could you add a few more lines since the provided code does not have a data definition, import statements, and missing functions?

**Reply by tahsintahsin** [reply, marked as answer]
Sorry @nzw0301 we couldn't update you on the matter as we went into a holiday period. 
Eventually, issue with OOM is solved when we stopped using HF trainer class and we started using PyTorch code to write a training block. 
Now optuna works as expected, with no OOM issues, at the end of each trial, we clear up the model and optimizer states, and all is fine 
I think the issue was stemming from HF Trainer class, but since our problem is solved now, we won't dive deeper into that. 
To sum up, thanks for all your help again, we are using optuna just fine :)

**Reply by nzw0301** [reply]
@tahsintahsin No worries, holiday is all we need :) Thank you for letting me know that. I'm glad to hear that the OOM issue has been resolved and it did not from optuna. 

Cheers,
